aws_region          = "ap-south-1"
project_name        = "terraform-assessment"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
availability_zone   = "ap-south-1b"
instance_type       = "t2.micro"
my_ip_cidr          = "YOUR_PUBLIC_IP/32"
